#ifndef FCTVIEWPLUGIN_GLOBAL_H
#define FCTVIEWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FCTVIEWPLUGIN_LIBRARY)
#  define FCTVIEWPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FCTVIEWPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FCTVIEWPLUGIN_GLOBAL_H
